export const clinics = [
    // {
    //     id:''
    //     title:'',
    //     description:'',
    //     imageUrl:'',    //assets/images/cutezero_sketch_2.jpg
    //     imageAlt:'',
    // phoneNumber:'',
    //     whatsAppNumber:'',
    //     telegramNumber:'',
    //     email:'',
    //     rating:0,   // number type 
    //     pricing :'',
    // gmapUrl:'',
    // },
    {
        id: '1',
        title: 'MKCG',
        description: 'No 1 Hospital in Ganjam',
        imageUrl: 'https://www.mkcgmch.org/images/logo.png',
        rating: 4.1,
        gmapUrl: 'https://goo.gl/maps/KYucT7VYAaQNmLjP7',
        phoneNumber: '0680 229 2746',
        country: 'India',
        stateUT: 'Odisha',
        distCity: 'Ganjam',
        area: '',
        localArea: '',
        pin: '',
        longitude: '',
        lattitude: '',
    },
    {
        id: '2',
        title: 'PHL Clinic ପି.ଏଚ୍.ଏଲ୍ କ୍ଲିନିକ୍',
        description: 'Best OPD in Berhampur',
        imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipPpV1kqibOpR-akws6OK4tAD2gvxjBTQhtL4TJV=w408-h652-k-no',
        rating: 4.2,
        gmapUrl: 'https://maps.app.goo.gl/K3kfVritzStgpQ537',
        phoneNumber: '9911 303 040',
        whatsAppNumber:'9911303040',
    },
    {
        id: '3',
        title: 'Bhagabati Physiotherapy Clinic',
        description: 'Physeo clinic, phone2: 7978012890',
        imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOLY0p8nFXOKxg_7bVMSv1s_2kxOy-Zbm_sfmUU=w426-h240-k-no',
        rating: 4.3,
        gmapUrl: 'https://maps.app.goo.gl/TEqUKg5SBMyMRAcv8',
        phoneNumber: '085990 65999',
        whatsAppNumber:'8599065999',
    },
    {
        id: '4',
        title: 'MOM N KIDS CLINIC',
        description: 'Physeo clinic, phone2: 7978012890',
        imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipMSmkfmJsoWCIBXZe0egxQutYM91J0xqYGu0tii=w128-h128-p-k-no',
        rating: 4.3,
        gmapUrl: 'https://goo.gl/maps/94ipM37TJcTDKEn86',
        phoneNumber: '09692921110',
        whatsAppNumber:'09692921110',
    },
]
